### PR TITLE
Added convenience method to get a node in a document by path.

### PR DESCRIPTION
**Pull request by slaff**

### CODE REVIEW

**Comment by mikee47** [comment]
@slaff Thanks for this, great idea. I've reworked it a little and pushed to develop branch, if you want to try it out?

**Comment by slaff** [comment]
@mikee47 The changes in your develop branch look great to me. Just change in the headers of the test app "This file is part of the FlashString Library" with the appropriate one. Once ready and merged in your master branch ping me so that I can update the used version also in Sming and rebase the DIAL client PR.

**Comment by mikee47** [comment]
@slaff OK merged

**Comment by slaff** [comment]
@mikee47 I am having a problem with the new getNode method. I was naively thinking that the code below with path `/s:Body/u:GetMuteResponse/CurrentMute` will help me get the CurrentMute node. Any recommendations how to change the path in order to get to the CurrentMute? Notice that we have two namespaces here. 
```C++
String xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>"
"<s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">"
 "<s:Body>"
  "<u:GetMuteResponse xmlns:u=\"urn:schemas-upnp-org:service:RenderingControl:1\">"
   "<CurrentMute>0</CurrentMute>"
  "</u:GetMuteResponse>"
 "</s:Body>"
"</s:Envelope>";

XML::Document doc;
XML::deserialize(doc, (char *)xml.c_str());

auto node = XML::getNode(doc, "/s:Body/u:GetMuteResponse/CurrentMute");
if(node != nullptr) {
	Serial.printf("State: %d", atoi(node->value()));
}
```

**Comment by mikee47** [comment]
You'll need to do it in two steps. Take a look at https://github.com/mikee47/Sming-RapidXML/blob/master/test/app/node.cpp.

Also, this is where `SOAP::Envelope` should be able to do the work rather than messing about with XML. If it doesn't do what you need, let's update it!

**Comment by slaff** [comment]
I was hoping to have a very simplified/limited [XPath](https://www.w3schools.com/xml/xpath_syntax.asp) way to get a node. Doing it in two steps should work but it does not feel very user-friendly.

**Comment by mikee47** [comment]
Parsing an envelope is boilerplate stuff which the library will do. It handles it for hosted devices (see `UPnP::ActionInfo`) but requires developing for ControlPoint use. I'll start a PR for this.

**Pull request merged**
